import { env } from "./env";
const mem: Record<string, any[]> = { clips: [], connections: [], settings: [], ai_usage: [], post_results: [], analytics_snapshots: [] };
function ready(){ return !!(env("SUPABASE_URL") && env("SUPABASE_SERVICE_ROLE_KEY")); }
async function req(path:string, init:RequestInit={}){ const url = `${env("SUPABASE_URL")}/rest/v1/${path}`; const key = env("SUPABASE_SERVICE_ROLE_KEY"); const r = await fetch(url,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})},cache:"no-store"}); if(!r.ok) throw new Error(await r.text()); if(r.status===204) return []; return r.json(); }
export async function listRows<T>(table:string, query="order=created_at.desc"):Promise<T[]>{ if(!ready()) return (mem[table]||[]) as T[]; return req(`${table}?${query}`); }
export async function insertRow<T>(table:string, row:any):Promise<T>{ if(!ready()){ const item={id:row.id||crypto.randomUUID(), created_at:new Date().toISOString(), ...row}; mem[table]=[item,...(mem[table]||[])]; return item as T;} const rows=await req(table,{method:"POST",body:JSON.stringify(row)}); return rows[0] as T; }
export async function updateRow<T>(table:string, id:string, row:any):Promise<T>{ if(!ready()){ mem[table]=(mem[table]||[]).map(x=>x.id===id?{...x,...row,updated_at:new Date().toISOString()}:x); return mem[table].find(x=>x.id===id) as T;} const rows=await req(`${table}?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(row)}); return rows[0] as T; }
export async function upsertSetting(key:string, value:any){ if(!ready()){ mem.settings=[...(mem.settings||[]).filter(x=>x.key!==key),{key,value,updated_at:new Date().toISOString()}]; return {key,value}; } const rows=await req("settings",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({key,value,updated_at:new Date().toISOString()})}); return rows[0]; }
export async function getSetting<T>(key:string, fallback:T):Promise<T>{ if(!ready()) return ((mem.settings||[]).find(x=>x.key===key)?.value ?? fallback) as T; const rows=await req(`settings?key=eq.${encodeURIComponent(key)}&limit=1`); return (rows[0]?.value ?? fallback) as T; }
export async function saveConnection(provider:string, data:any){ if(!ready()){ mem.connections=[...(mem.connections||[]).filter(x=>x.provider!==provider),{provider,...data,connected_at:new Date().toISOString()}]; return;} await req("connections",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({provider,...data,connected_at:new Date().toISOString()})}); }
export async function getConnection(provider:string){ const rows= await listRows<any>("connections",`provider=eq.${provider}&limit=1`); return rows[0] || null; }
